---
- name: Create users in loop
  hosts: localhost
  tasks:
    - name: Create users with sequence
      user:
        name : "user{{item}}"
        groups: [students, operator]
        shell: /bin/bash
        password: "user{{item}}@123"
        state: present
      with_sequence: start=18 end=20
      register: users
    - debug:
        msg: "{{users}}"
