---
- name: Role calling Playbook
  hosts: localhost
  tasks:
    - name: calling Role A Installer
      include_role:
        name: roleA
      tags: installer

    - name: calling Role A Maven
      include_role:
        name: roleA
      tags: maven
