---
- name: Role calling Playbook
  hosts: localhost
  tasks:
    - name: calling Role A
      include_role:
        name: roleA
        tasks_from: apt.yml
      tags: installer

    - name: calling Role A
      include_role:
        name: roleA
        tasks_from: maven.yml
      tags: maven
